site_name: Basket Viz Documentation
theme:
  name: material

nav:
  - Home: index.md
  - Shot Charts:
      - Overview: shot_charts/overview.md
      - Static Scatter: shot_charts/static_scatter.md
      - Animated Scatter: shot_charts/animated_scatter.md
      - Euroleague Scatter: shot_charts/euroleague_scatter.md
      - Heatmap: shot_charts/heatmap.md

docs_dir: docs